config/routes.rb
Cinematron::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root :to => 'home#index'

  resources :movies do
    resources :comments
    resources :reviews
    member do
      post :rate
    end
    get 'page/:page', action: :index, on: :collection
  end
  get '/movies_search', action: :search, controller: :movies
  
  resources :people

  devise_for :users
  get "users/new"

end

app/models/person.rb
# == Schema Information
#
# Table name: people
#
#  id          :integer          not null, primary key
#  first_name  :string(255)
#  middle_name :string(255)
#  last_name   :string(255)
#  birth_date  :date
#  country_id  :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Person < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :middle_name, :birth_date, :country_id, :profession_id

  belongs_to :country
  has_many :creators
  has_many :professions, through: :creators
  has_many :movies, through: :creators

  def to_s
    first_name.to_s + ' ' + middle_name.to_s + ' ' + last_name.to_s
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  load_and_authorize_resource
  
  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new
    @countries = Country.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
    @countries = Country.all
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end
end

app/views/people/_form.html.haml
.row
  .span5.offset1
    - if @person.errors.any?
      .alert.alert-error
        The form contains errors.


%br
= form_for @person, html: { class: 'form-horizontal' } do |f|
  = render layout: 'shared/field', locals: { f: f, resource: @person, field_name: :first_name } do
    = f.text_field :first_name

  = render layout: 'shared/field', locals: { f: f, resource: @person, field_name: :middle_name } do
    = f.text_field :middle_name

  = render layout: 'shared/field', locals: { f: f, resource: @person, field_name: :last_name } do
    = f.text_field :last_name

  = render layout: 'shared/field', locals: { f: f, resource: @person, field_name: :birth_date } do
    = f.date_select :birth_date, start_year: 1850, end_year: Time.now.year  

  = render layout: 'shared/field', locals: { f: f, resource: @person, field_name: :country } do
    = f.collection_select(:country_id, @countries, :id, :name, prompt: 'Select country')

  .form-actions
    = f.submit nil, class: 'btn btn-primary'
    = link_to t('.cancel', default: t("helpers.links.cancel")), people_path, class: 'btn'

app/views/people/edit.html.haml
- title 'Edit movie'
- model_class = Person
.page-header
  %h2= yield :title

= render 'form'

app/views/people/index.html.haml
- title 'People'
- model_class = Person
.page-header
  %h2= yield :title

.span7
  %table.table.table-striped
    %thead
      %tr
        %th= 'Name'
        %th= 'Birth date'
        %th= 'Country'
        - if can? :manage, @movies
          %th= 'Actions'
    %tbody
      - @people.each do |person|
        %tr
          %td= link_to person.to_s, person_path(person)
          %td= person.birth_date
          %td= person.country.name if person.country
          - if can? :manage, Person
            %td          
              = link_to 'Edit', edit_person_path(person), class:'btn btn-mini'
              = link_to 'Destroy',
                          person_path(person),
                          method: :delete,
                          data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
                          class: 'btn btn-mini btn-danger'
  - if can? :manage, Person
    = link_to t('.new', :default => t("helpers.links.new")),
                new_person_path,
                class: 'btn btn-primary'

app/views/people/new.html.haml
- title 'New person'
- model_class = Person
.page-header
  %h2= yield :title

= render 'form'

app/views/people/show.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:first_name) %>:</strong></dt>
  <dd><%= show_field @person.first_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:middle_name) %>:</strong></dt>
  <dd><%= show_field @person.middle_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= show_field @person.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:birth_date) %>:</strong></dt>
  <dd><%= show_field @person.birth_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:country_id) %>:</strong></dt>
  <dd><%= if @person.country then @person.country.name else 'None' end %></dd>
</dl>

<div class="form-actions">
  <%= link_to 'Back to people', people_path, :class => 'btn' %>
  <% if can? :manage, Person %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_person_path(@person), :class => 'btn' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                person_path(@person),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
  <% end %>
</div>