config/routes.rb
Cinematron::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root :to => 'home#index'

  resources :movies do
    resources :comments
    resources :reviews
    member do
      post :rate
    end
    get 'page/:page', action: :index, on: :collection
  end
  get '/movies_search', action: :search, controller: :movies
  
  resources :people

  devise_for :users
  get "users/new"

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  load_and_authorize_resource

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.page(params[:page]).per(8).order('release_date DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.json { render json: @movies }
    end
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @comment = Comment.new
    @review = Review.new
    @movie = Movie.find(params[:id])
    @commentable = @movie
    @comments = @commentable.comments.order(:created_at)
    @reviewable = @movie
    @reviews = @reviewable.reviews.order(:created_at)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/new
  # GET /movies/new.json
  def new
    @movie = Movie.new
    @genres = Genre.all
    @countries = Country.all
    @professions = Profession.all
    @people = Person.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
    @genres = Genre.all
    @countries = Country.all
    @professions = Profession.all
    @people = Person.all
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(params[:movie])
    @genres = Genre.all
    @countries = Country.all
    @professions = Profession.all
    @people = Person.all

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render json: @movie, status: :created, location: @movie }
      else
        @countries = Country.all
        format.html { render action: "new" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /movies/1
  # PUT /movies/1.json
  def update
    @movie = Movie.find(params[:id])
    @genres = Genre.all
    @countries = Country.all
    @professions = Profession.all
    @people = Person.all

    respond_to do |format|
      if @movie.update_attributes(params[:movie])
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :no_content }
    end
  end

  def rate
    @movie = Movie.find(params[:id])
    @movie.rate(params[:stars], current_user, params[:dimension])
    
    respond_to do |format|
      format.js
    end
  end

  def search
    @movies = Movie.search(params)
    @countries = Country.all
    @genres = Genre.all
    @people = Person.all
  end
end

app/views/movies/_creator_fields.html.haml
.nested-fields
  .control-group
    .form-inline
      = f.collection_select(:profession_id, @professions, :id, :name, prompt: 'Select a profession')
      = f.collection_select(:person_id, @people, :id, :to_s, prompt: 'Select a person')
      = link_to_remove_association "remove", f, class: 'btn btn-danger btn-small'
      %span.help-inline= @movie.errors['creators.movie_id'].first

app/views/movies/_errors.html.erb
<% if @movie.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@movie.errors.count, "error") %>.
    </div>
    <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/movies/_form.html.haml
.row
  .span5.offset1
    - if @movie.errors.any?
      .alert.alert-error
        The form contains errors.

%br
= form_for @movie, html: { class: 'form-horizontal' } do |f|

  = render layout: 'shared/field', locals: { f: f, resource: @movie, field_name: :name } do
    = f.text_field :name, autofocus: true

  = render layout: 'shared/field', locals: { f: f, resource: @movie, field_name: :poster } do
    = f.text_field :poster, placeholder: "URL"

  = render layout: 'shared/field', locals: { f: f, resource: @movie, field_name: :trailer } do
    = f.text_field :trailer, placeholder: "URL"

  = render layout: 'shared/field', locals: { f: f, resource: @movie, field_name: :min_age } do
    = f.number_field :min_age

  = render layout: 'shared/field', locals: { f: f, resource: @movie, field_name: :length } do
    = f.number_field :length

  = render layout: 'shared/field', locals: { f: f, resource: @movie, field_name: :year } do
    = f.date_select :release_date

  = render layout: 'shared/field', locals: { f: f, resource: @movie, field_name: :country } do
    = f.collection_select(:country_id, @countries, :id, :name, prompt: 'Select country')

  %div{ class: ['control-group', "#{'error' if @movie.errors['genre_movie_joins.genre_id'].any?}"] }
    = f.label :genres, class: 'control-label'
    .controls
      = f.fields_for :genre_movie_joins do |builder|
        = render 'genre_movie_join_fields', f: builder
      .links
        = link_to_add_association 'Add genre', f, :genre_movie_joins, class: 'btn btn-small'
        
  %div{ class: ['control-group', "#{'error' if @movie.errors['creators.movie_id'].any?}"] }
    = f.label :people, class: 'control-label'
    .controls
      = f.fields_for :creators do |builder|
        = render 'creator_fields', f: builder
      .links
        = link_to_add_association 'Add person', f, :creators, class: 'btn btn-small'

  = render layout: 'shared/field', locals: { f: f, resource: @movie, field_name: :info } do
    = f.text_area :info, class: 'input-xxlarge',
                                rows: 5,
                                placeholder: 'Movie description...'

  .form-actions
    = f.submit nil, class: 'btn btn-primary'
    = link_to t('.cancel', default: t("helpers.links.cancel")), movies_path, class: 'btn'

app/views/movies/_genre_movie_join_fields.html.haml
.nested-fields
  .control-group
    .form-inline
      = f.collection_select(:genre_id, @genres, :id, :name, prompt: 'Select a genre')
      = link_to_remove_association "remove", f, class: 'btn btn-danger btn-small'
      %span.help-inline= @movie.errors['genre_movie_joins.genre_id'].first

app/views/movies/_genres_list.html.haml
- if genres.empty?
  = 'None'
- else
  - genres, last = genres[0..-2], genres.last
  - genres.each do |genre|
    = genre.name
    |
  = last.name

app/views/movies/_people_list.html.haml
- if people.empty?
  = 'None'
- else
  - people, last = people[0..-2], people.last
  - people.each do |person|
    = link_to person, person_path(person)
    ,
  = link_to last, person_path(last)

app/views/movies/_summary.html.haml
.text-center
  .row{ style: "margin:0 auto; height: 55px;" }
    .wrap
      %h4= movie.name
  .row{ style: "margin:0 auto;" }
    = link_to (image_tag movie.poster, style: "max-height:385px; max-width:100%;", |
                onError: "this.onerror=null; |
                          this.src='https://lh4.googleusercontent.com/-iHcpcxQcoJ4/UWZNGLcFV2I/AAAAAAAACNE/uNyPZ5j31iY/s330/noImageAvailable.JPG';"), |
              movie_path(movie)
  .row{ style: "margin:0 auto;" }
    = ratings_for movie, :static
  .row{ style: "margin:0 auto;" }
    = render 'genres_list', genres: movie.genres

app/views/movies/edit.html.haml
- title 'Edit movie'
- model_class = Movie
.page-header
  %h2= yield :title

= render 'form'

app/views/movies/index.html.haml
- title 'Movies'
- model_class = Movie
.page-header
  %h2= yield :title

#movies= render 'movies'

app/views/movies/index.js.erb
$('#movies').html('<%= j render "movies" %>');

app/views/movies/new.html.haml
- title 'New movie'
- model_class = Movie
.page-header
  %h2= yield :title

= render 'form'

%h3= @movie.errors.each { |error| error }

app/views/movies/rate.js.erb
$('.ratings').html('<%= j render "ratings" %>');
$('.<%= current_user.name %>-rating').html('<%= j ratings_for @movie, current_user, show_user_rating: true %>');

app/views/movies/search.html.haml
- title 'Movies search'

.page-header
  %h2= 'Search'

= form_tag({ action: :search, controller: :movies }, method: :get) do
  .form-horizontal
    .row
      .span
        .control-group
          .control-label= label_tag 'Name:'
          .controls
            = text_field_tag :name, params[:name]
    .row
      .span4
        .control-group
          .control-label= label_tag 'Genre:'
          .controls
            = collection_select :movie, :genre_id, @genres, :id, :name, { prompt: 'Select genre', |
                                      selected: if params[:movie].present? then params[:movie][:genre_id] end }
      .span4
        .control-group
          .control-label= label_tag 'Country:'
          .controls
            = collection_select :movie, :country_id, @countries, :id, :name, { prompt: 'Select country', |
                                        selected: if params[:movie].present? then params[:movie][:country_id] end }
    .row
      .span4
        .control-group
          .control-label= label_tag 'Min age:'
          .controls
            = number_field_tag :min_age, params[:min_age]
            %br
            .form-inline
              = label_tag 'less'
              = radio_button_tag :min_age_op, '<', params[:min_age].present? && params[:min_age_op] == '<'
              = label_tag 'equal'
              = radio_button_tag :min_age_op, '=', params[:min_age].present? && params[:min_age_op] == '=' || !params[:min_age].present?
              = label_tag 'more'
              = radio_button_tag :min_age_op, '>', params[:min_age].present? && params[:min_age_op] == '>'
      .span4
        .control-group
          .control-label= label_tag 'Year:'
          .controls
            = number_field_tag :year, params[:year]
            %br
            .form-inline
              = label_tag 'less'
              = radio_button_tag :year_op, '<', params[:year].present? && params[:year_op] == '<'
              = label_tag 'equal'
              = radio_button_tag :year_op, '=', params[:year].present? && params[:year_op] == '=' || !params[:year].present?
              = label_tag 'more'
              = radio_button_tag :year_op, '>', params[:year].present? && params[:year_op] == '>'
    .row
      .span
        .control-group
          .control-label= label_tag 'Person:'
          .controls
            = collection_select :movie, :person_id, @people, :id, :to_s, { prompt: 'Select person', |
                                          selected: if params[:movie].present? then params[:movie][:person_id] end }
    .row
      %div{style: "height: 20px;"}
      .offset1= submit_tag 'Search', class: 'btn btn-primary btn-large'

%div{style: "height: 20px;"}
.span10.offset1
  %table.table.table-striped.table-hover
    %thead
      %tr
        %th Name
        %th Min age
        %th Length
        %th Year
        %th Country
        - if can? :manage, Movie
          %th Actions
    %tbody
      - @movies.each do |movie|
        %tr
          %td= link_to movie.name, movie_path(movie)
          %td= movie.min_age
          %td= movie.length
          %td= movie.release_date
          %td= movie.country.name if movie.country
          - if can? :manage, Movie
            %td
              = link_to 'Edit', edit_movie_path(movie), class:'btn btn-mini'
              = link_to 'Destroy',
                          movie_path(movie),
                          method: :delete,
                          data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
                          class: 'btn btn-mini btn-danger'

app/views/movies/show.html.haml
- title @movie.name
- model_class = Movie

.row
  .span4
    = image_tag @movie.poster, onError: "this.onerror=null;this.src='https://lh4.googleusercontent.com/-iHcpcxQcoJ4/UWZNGLcFV2I/AAAAAAAACNE/uNyPZ5j31iY/s330/noImageAvailable.JPG';"

    %div{style: "height: 20px;"}
    .btn-group
      = link_to 'Back to movies', movies_path, class: 'btn'
      - if can? :manage, Movie
        = link_to 'Edit', edit_movie_path(@movie), class: 'btn'
        = link_to 'Delete', @movie, method: :delete, confirm: 'Are you sure?', class: 'btn btn-danger'

  .span8
    .row
      .span3
        %h2= yield :title
        %a.trailer{ href: @movie.trailer } Click here to watch the trailer
        %div{style: "height: 20px;"}
        = render 'ratings'
        %div{style: "height: 20px;"}
        %strong Min age:
        = show_field @movie.min_age
        %br
        %strong Length:
        = show_field @movie.length
        %br
        %strong Country:
        = if @movie.country then @movie.country.name else 'None' end
        %br
        %strong Release date:
        = show_field @movie.release_date
      
      %div{style: "height: 20px;"}
      .span5
        .well.well-small
          %strong Genres:
          %p= render 'genres_list', genres: @movie.genres
        .well.well-small
          %strong Directors:
          %p= render 'people_list', people: @movie.people_with_profession('director')
        .well.well-small
          %strong Writers:
          %p= render 'people_list', people: @movie.people_with_profession('screenwriter')
        .well.well-small
          %strong Producers:
          %p= render 'people_list', people: @movie.people_with_profession('producer')
      
    .row
      .span8
        .well.well-small
          %strong Actors:
          %p= render 'people_list', people: @movie.people_with_profession('actor')
        .well.well-small
          %strong Info:
          %p= show_field @movie.info

%div{style: "height: 20px;"}
.row
  .tabbable
    %ul.nav.nav-tabs
      %li.active
        %a{ href: "#reviews_tab", 'data-toggle' => 'tab' } Reviews
      %li 
        %a{ href: "#discussion_tab", 'data-toggle' => 'tab' } Discussion

    .tab-content
      #reviews_tab.tab-pane.active
        .media.span6
          %h3 Reviews
          .reviews
            - @reviews.each do |review|
              = render "reviews/review", review: review
          %div{ class: 'review-form' }
            - if user_signed_in?
              - if @reviews.any? { |r| r.user_id == current_user.id }
                .alert.alert-info
                  You already left a review.
              - else
                = render "reviews/form", reviewable: @reviewable, review: @review
            - else
              .alert.alert-info
                Sign in to leave a review.
      #discussion_tab.tab-pane
        .media.span6
          %h3 Comments
          .comments
            - @comments.each do |comment|
              = render "comments/comment", comment: comment
          - if user_signed_in?
            = render "comments/form"
          - else
            .alert.alert-info
              Sign in to leave a comment.